language: node_js
node_js:
- "0.8"
- "0.10"

env:
  global:
    # NPM_KEY
    - secure: aOHRXELamyzmgttmZszXZER7w4XNrXHvuE4bFB/s3jWs9pk/z4DG72y+33KQN8e+IOcqCgoVmIqV1CnARJCZHh4VkqW1qPTQpKLHDKGf4v1O2wJDM/+DUhVRig+OU2ehZj/xkvnUn05tZ1ptlYlof3Xhb5ads4sVX30INmIgpxw=

# NPM Deploy
deploy:
  provider: npm
  email: "gustavo@injoin.com.br"
  api_key: "${NPM_KEY}"
  on:
    tags: true